"""create bronze tables

Revision ID: 00a797489564
Revises: 
Create Date: 2026-02-21 14:47:53.615598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a797489564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('job_code', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('job_start_date', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('organization_name', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Text(), nullable=True),
    sa.Column('department_name', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('hire_date', sa.Text(), nullable=True),
    sa.Column('recent_hire_date', sa.Text(), nullable=True),
    sa.Column('anniversary_date', sa.Text(), nullable=True),
    sa.Column('term_date', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Text(), nullable=True),
    sa.Column('work_email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('manager_employee_id', sa.Text(), nullable=True),
    sa.Column('manager_employee_name', sa.Text(), nullable=True),
    sa.Column('fte_status', sa.Text(), nullable=True),
    sa.Column('is_per_deim', sa.Text(), nullable=True),
    sa.Column('cell_phone', sa.Text(), nullable=True),
    sa.Column('work_phone', sa.Text(), nullable=True),
    sa.Column('scheduled_weekly_hour', sa.Text(), nullable=True),
    sa.Column('active_status', sa.Text(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('clinical_level', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_table('raw_timesheet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Text(), nullable=True),
    sa.Column('department_name', sa.Text(), nullable=True),
    sa.Column('home_department_id', sa.Text(), nullable=True),
    sa.Column('home_department_name', sa.Text(), nullable=True),
    sa.Column('pay_code', sa.Text(), nullable=True),
    sa.Column('punch_in_comment', sa.Text(), nullable=True),
    sa.Column('punch_out_comment', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Text(), nullable=True),
    sa.Column('punch_apply_date', sa.Text(), nullable=True),
    sa.Column('punch_in_datetime', sa.Text(), nullable=True),
    sa.Column('punch_out_datetime', sa.Text(), nullable=True),
    sa.Column('scheduled_start_datetime', sa.Text(), nullable=True),
    sa.Column('scheduled_end_datetime', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_timesheet', schema='bronze')
    op.drop_table('raw_employee', schema='bronze')
    # ### end Alembic commands ###
