"""create silver tables

Revision ID: 16bc36f51270
Revises: 00a797489564
Create Date: 2026-02-21 16:35:03.734810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bc36f51270'
down_revision: Union[str, Sequence[str], None] = '00a797489564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='silver'
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['silver.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'organization_id', name='uq_dept_code_org'),
    schema='silver'
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('job_code', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_start_date', sa.Date(), nullable=True),
    sa.Column('fte_status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_weekly_hour', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('clinical_level', sa.String(length=100), nullable=True),
    sa.Column('is_per_deim', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('recent_hire_date', sa.Date(), nullable=True),
    sa.Column('anniversary_date', sa.Date(), nullable=True),
    sa.Column('term_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('cell_phone', sa.String(length=50), nullable=True),
    sa.Column('work_phone', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('manager_employee_id', sa.String(length=50), nullable=True),
    sa.Column('manager_employee_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['silver.department.id'], ),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['silver.employee.client_employee_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['silver.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_employee_id'),
    schema='silver'
    )
    op.create_index('ix_employee_active', 'employee', ['active_status'], unique=False, schema='silver')
    op.create_index('ix_employee_dept', 'employee', ['department_id'], unique=False, schema='silver')
    op.create_index('ix_employee_hire_date', 'employee', ['hire_date'], unique=False, schema='silver')
    op.create_table('timesheet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('home_department_id', sa.String(length=50), nullable=True),
    sa.Column('home_department_name', sa.String(length=255), nullable=True),
    sa.Column('pay_code', sa.String(length=100), nullable=True),
    sa.Column('punch_apply_date', sa.Date(), nullable=False),
    sa.Column('punch_in_datetime', sa.DateTime(), nullable=True),
    sa.Column('punch_out_datetime', sa.DateTime(), nullable=True),
    sa.Column('scheduled_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('punch_in_comment', sa.String(length=100), nullable=True),
    sa.Column('punch_out_comment', sa.String(length=100), nullable=True),
    sa.Column('is_late_arrival', sa.Boolean(), nullable=True),
    sa.Column('is_early_departure', sa.Boolean(), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('is_unscheduled', sa.Boolean(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_employee_id'], ['silver.employee.client_employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    op.create_index('ix_timesheet_date', 'timesheet', ['punch_apply_date'], unique=False, schema='silver')
    op.create_index('ix_timesheet_employee', 'timesheet', ['client_employee_id'], unique=False, schema='silver')
    op.create_index('ix_timesheet_employee_date', 'timesheet', ['client_employee_id', 'punch_apply_date'], unique=False, schema='silver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timesheet_employee_date', table_name='timesheet', schema='silver')
    op.drop_index('ix_timesheet_employee', table_name='timesheet', schema='silver')
    op.drop_index('ix_timesheet_date', table_name='timesheet', schema='silver')
    op.drop_table('timesheet', schema='silver')
    op.drop_index('ix_employee_hire_date', table_name='employee', schema='silver')
    op.drop_index('ix_employee_dept', table_name='employee', schema='silver')
    op.drop_index('ix_employee_active', table_name='employee', schema='silver')
    op.drop_table('employee', schema='silver')
    op.drop_table('department', schema='silver')
    op.drop_table('organization', schema='silver')
    # ### end Alembic commands ###
