"""add rejected timesheet table

Revision ID: 7010b2df9bab
Revises: acaafdb3cd28
Create Date: 2026-02-23 21:38:43.632327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7010b2df9bab'
down_revision: Union[str, Sequence[str], None] = 'acaafdb3cd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_timesheet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.Text(), nullable=True),
    sa.Column('punch_apply_date', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rejected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_timesheet', schema='bronze')
    # ### end Alembic commands ###
