"""create gold and auth tables

Revision ID: acaafdb3cd28
Revises: 16bc36f51270
Create Date: 2026-02-22 21:26:55.384460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaafdb3cd28'
down_revision: Union[str, Sequence[str], None] = '16bc36f51270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('kpi_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('total_shifts', sa.Integer(), nullable=True),
    sa.Column('late_arrival_count', sa.Integer(), nullable=True),
    sa.Column('early_departure_count', sa.Integer(), nullable=True),
    sa.Column('overtime_count', sa.Integer(), nullable=True),
    sa.Column('late_arrival_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_table('kpi_early_attrition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('total_hires', sa.Integer(), nullable=True),
    sa.Column('early_attrition_count', sa.Integer(), nullable=True),
    sa.Column('early_attrition_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_table('kpi_headcount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date'),
    schema='gold'
    )
    op.create_table('kpi_rolling_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_employee_id', sa.String(length=50), nullable=False),
    sa.Column('punch_apply_date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rolling_avg_7d', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_table('kpi_tenure_by_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('avg_tenure_years', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    op.create_table('kpi_turnover',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('terminations', sa.Integer(), nullable=False),
    sa.Column('turnover_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_turnover', schema='gold')
    op.drop_table('kpi_tenure_by_department', schema='gold')
    op.drop_table('kpi_rolling_hours', schema='gold')
    op.drop_table('kpi_headcount', schema='gold')
    op.drop_table('kpi_early_attrition', schema='gold')
    op.drop_table('kpi_attendance', schema='gold')
    op.drop_table('api_user', schema='auth')
    # ### end Alembic commands ###
